app/projects/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FileField, TextAreaField, SelectField
from wtforms.validators import  DataRequired



class AddEditProjectForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    prefix = StringField('Prefix for trackers', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/projects/__init__.py
from flask import Blueprint

bp = Blueprint('projects', __name__)

from app.projects import routes

app/projects/routes.py
from app.projects import bp
from flask import url_for, request, render_template, current_app, flash,redirect, jsonify
from flask_login import login_required, current_user
from app.projects.forms import AddEditProjectForm
from app.projectmodel import TrkProject
import os



@bp.route('/projectlist')
@login_required
def projectlist():
    if not current_user.admin:
        return redirect(url_for('trackerapp.index'))
    page = request.args.get('page', 1, type=int)
    projects = TrkProject.get_list_projects(page, int(current_app.config['PROJECTS_PER_PAGE']))
    prev_url = url_for('projects.projectlist', page=projects.prev) if projects.has_prev else None
    next_url = url_for('projects.projectlist', page=projects.next) if projects.has_next else None
    return render_template('projects/projectlist.html', title='projects',
                       prev_url=prev_url, next_url=next_url, projects=projects.projects )



@bp.route('/project_info/<id>', methods=['GET', 'POST'])
@login_required
def project_info(id):
    
    project = TrkProject.get_project(id)
    
    if project is None:
        flash('project with id {} does not exist'.format(id))
        return redirect(url_for('projects.projectlist'))
    if request.method == 'POST':
        if request.form['action'] == 'edit':
            return redirect(url_for('projects.project_edit', id=project.id))
        elif request.form['action'] == 'back': 
            return redirect(url_for('projects.projectlist'))
        else:
            flash('Something strange happened here')
            return redirect(url_for('projects.projectlist'))
    else:
        return render_template('projects/project_info.html', project=project, title=project.name)


@bp.route('/project_edit/<id>', methods=['GET', 'POST'])
@login_required
def project_edit(id):
    project = TrkProject.get_project(id)
    
    if project is None:
        flash('project with id {} does not exist'.format(id))
        return redirect(url_for('projects.projectlist'))
    form = AddEditProjectForm(obj=project)
    if form.validate_on_submit():
        project.name = form.name.data
        project.description = form.description.data
        project.prefix = form.prefix.data
        project.update_project()
        flash('Project  {} updated'.format(project.name))
        return redirect(url_for('projects.projectlist'))
    else:
        return render_template('projects/project_edit.html', form=form,project=project, title=project.name)


@bp.route('/add_project', methods=['GET', 'POST'])
@login_required
def add_project():
    form = AddEditProjectForm()
    if form.validate_on_submit():
        project=TrkProject.create_project(form.name.data, form.description.data,form.prefix.data)
        return redirect(url_for('projects.project_info', id= project.id))
    return render_template('projects/add_project.html', form=form, title='Add project')

app/templates/projects/add_project.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Create Project</h1>
<div class="row">
    <div class="col-md-4">
        <form class="form form-vertical" method="post" role="form" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens="only") }}
            {{ wtf.form_field(form.name, class='form-control', placeholder='Name')}}
			<br>
			{{ wtf.form_field(form.prefix, class='form-control', placeholder='Prefix')}}
			{{ wtf.form_field(form.description, class='form-control', placeholder='Description')}}
            <br>
            {{ wtf.form_field(form.submit, class='btn btn-success') }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/projects/project_edit.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Update {{ project.name }}</h1>
<div class="row">
    <div class="col-md-4">
        <form class="form form-vertical" method="post" role="form" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens="only") }}
            {{ wtf.form_field(form.name, class='form-control', placeholder='Name')}}
			<br>
			{{ wtf.form_field(form.prefix, class='form-control', placeholder='Prefix')}}
			{{ wtf.form_field(form.description, class='form-control', placeholder='Description')}}
            <br>
            {{ wtf.form_field(form.submit, class='btn btn-success') }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/projects/project_info.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}

<div class="container">
    <h1>{{  project.name }}</h1>
    <div class="row">
        <div class="col-lg-12 order-md-1">
            <ul class="list-group mb-1">
			<li class="list-group-item d-flex justify-content-between lh-condensed">
					<h6 class="my-0"><b>Prefix</b></h6>
					<small class="text-muted">{{ project.prefix }}</small>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
					<h6 class="my-0"><b>Description</b></h6>
					<small class="text-muted">{{ project.description }}</small>
				</li>
                <br>
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <form action="" method="POST" class=del-component>
                        <button class="btn btn-warning" name="action" value="edit">Edit</button>
                        <button class="btn btn-success" name="action" value="back">Back</button>
                    </form>
                    <br>
				</li>
            </ul>
        </div>
    </div>
</div>


{% endblock %}

app/templates/projects/projectlist.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Projects list</h1>
<a href="{{ url_for('projects.add_project') }}" class="btn btn-info" role="button">Add new Project</a>
<table class="table table-hover">
       <tr>
	   <th>
            Prefix
        </th>
        <th>
            Title
        </th>
        <th>
            Project Description
        </th>
    </tr>
    {% for project in projects %}

    <tr>
		<td class="project_prefix">
			{{ project.prefix }}
        </td>
        <td>
            <div class="project_name">
                <a href="{{ url_for('projects.project_info',id=project.id) }}">{{ project.name }}</a>
                <span hidden="True">{{ project.id }}</span>
            </div>
        </td>
		
		<td class="project_description">
			{{ project.description }}
        </td>
    </tr>
    {% endfor %}
</table>
<nav aria-label="...">
    <ul class="pager">
        <li class="previous {% if not prev_url %} disabled {% endif %}">
            <a href="{{ prev_url or '#' }}">
                <span aria-hidden="true">&larr;</span>Newer
            </a>
        </li>
        <li class="next {% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}">
                <span aria-hidden="true">&rarr;</span>Older
            </a>
        </li>
    </ul>
</nav>
{% endblock %}
{% block scripts %}
    {{ super() }}
{% endblock %}