app/authentication/forms.py
from app.usermodel import User
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, ValidationError,EqualTo


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Log in')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Request registration')

    def validate_username(self, username):
        u = User.find_user(username.data)
        if u is not None:
            raise ValidationError('Username already exists!')
        u = User.find_user_request(username.data)
        if u is not None:
            raise ValidationError('Username already requested registration!')


class AcceptRequestForm(FlaskForm):
    username = StringField('username')
    submit = SubmitField('Accept')

app/authentication/__init__.py
from flask import Blueprint

bp = Blueprint('authentication', __name__)

from app.authentication import routes

app/authentication/routes.py
from app.authentication import bp
from flask import url_for, request, render_template, redirect, flash
from flask_login import login_required, current_user, login_user, logout_user
from app.authentication.forms import LoginForm,RegistrationForm
from app.usermodel import User
from werkzeug.urls import url_parse


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('trackerapp.trackerlist',filter_tracker='open'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.find_user(form.username.data)
        if user is None or not user.check_password(form.password.data) or not user.enabled:
            flash('Incorrect user or password')
            return redirect(url_for('trackerapp.trackerlist',filter_tracker='open'))
        login_user(user, form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('trackerapp.index')
        return redirect(next_page)
    return render_template('authentication/login.html', title='Login', form=form)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('trackerapp.index'))


@bp.route('/admin')
@login_required
def admin():
    if current_user.admin and current_user.enabled:
        requests = User.get_list_user_requests()
        users = User.get_list_users()
        return render_template('authentication/admin.html', title='Admin', requests=requests, users=users)
    else:
        return redirect(url_for('trackerapp.index'))


@bp.route('/accept_request/<username>', methods=['POST'])
@login_required
def accept_request(username):
    if current_user.admin and current_user.enabled:
        user_request = User.find_user_request(username)
        if user_request is not None:
            User.accept_request(user_request)
            flash('user enabled')
        else:
            flash('user does not exists')
        return redirect(url_for('authentication.admin'))
    else:
        return redirect(url_for('trackerapp.index'))


@bp.route('/delete_request/<username>', methods=['POST'])
@login_required
def delete_request(username):
    if current_user.admin and current_user.enabled:
        user_request = User.find_user_request(username)
        if user_request is not None:
            User.delete_request(user_request)
            flash('request deleted')
        else:
            flash('user does not exists')
        return redirect(url_for('authentication.admin'))
    else:
        return redirect(url_for('trackerapp.index'))


@bp.route('/enable_user/<username>', methods=['POST'])
@login_required
def enable_user(username):
    if current_user.admin and current_user.enabled:
        user_request = User.find_user(username)
        if user_request is not None:
            user_request.enable()
            flash('user enabled')
        else:
            flash('user does not exists')
        return redirect(url_for('authentication.admin'))
    else:
        return redirect(url_for('trackerapp.index'))


@bp.route('/disable_user/<username>', methods=['POST'])
@login_required
def disable_user(username):
    if current_user.admin and current_user.enabled:
        user_request = User.find_user(username)
        if user_request is not None:
            user_request.disable()
            flash('user disabled')
        else:
            flash('user does not exists')
        return redirect(url_for('authentication.admin'))
    else:
        return redirect(url_for('trackerapp.index'))


@bp.route('/delete_user/<username>', methods=['POST'])
@login_required
def delete_user(username):
    if current_user.admin and current_user.enabled:
        user_request = User.find_user(username)
        if user_request is not None:
            user_request.delete()
            flash('user deleted')
        else:
            flash('user does not exists')
        return redirect(url_for('authentication.admin'))
    else:
        return redirect(url_for('trackerapp.index'))


@bp.route('/registration', methods=['POST', 'GET'])
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('trackerapp.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User()
        user.username = form.username.data
        user.set_password(form.password.data)
        user.request_registration()
        flash('Registration request registered')
        return redirect(url_for('trackerapp.index'))
    return render_template('authentication/registration.html', title='Register', form=form)

app/templates/authentication/admin.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Admin logins</h1>
<h2>Requests</h2>
<table class="table table-hover">
    {% for request in requests %}
   <tr>
        <td>
            {{request.username}}
        </td>
        <td>
            <form action="{{ url_for('authentication.accept_request', username=request.username) }}" method=post class=del-component>
                <button class="btn btn-success">
                    Accept
                </button>
            </form>
        </td>
       <td>
           <form action="{{ url_for('authentication.delete_request', username=request.username) }}" method=post class=del-component>
                <button class="btn btn-danger">
                    Delete
                </button>
            </form>
       </td>
    </tr>
    {% endfor %}
</table>
<br>
<h2>Users</h2>
<table class="table table-hover">
    {% for user in users %}
   <tr>
        <td>
            {{user.username}}
        </td>
       {% if user.admin == 'False' %}
        <td>
            {% if user.enabled %}
            <form action="{{ url_for('authentication.disable_user', username=user.username) }}" method=post class=del-component>
                <button class="btn btn-warning">
                    Disable
                </button>
            </form>
            {% else %}
            <form action="{{ url_for('authentication.enable_user', username=user.username) }}" method=post class=del-component>
                <button class="btn btn-success">
                    Enable
                </button>
            </form>
            {% endif %}
        </td>
       <td>
            <form action="{{ url_for('authentication.delete_user', username=user.username) }}" method=post class=del-component>
                <button class="btn btn-danger">
                    Delete
                </button>
            </form>
        </td>
       {% else %}
       <td></td><td></td>
       {% endif %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

app/templates/authentication/login.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Log in</h1>
<div class="row">
    <div class="col-md-4">
        <form class="form form-vertical" method="post" role="form">
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens="only") }}
            {{ wtf.form_field(form.username, class='form-control', placeholder='Your username...')}}
            {{ wtf.form_field(form.password, class='form-control', placeholder='Your password')}}
            {{ wtf.form_field(form.remember_me, class='form-checkbox') }}
            {{ wtf.form_field(form.submit, class='btn btn-success') }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/authentication/registration.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Request registration</h1>
<div class="row">
    <div class="col-md-4">
        <form class="form form-vertical" method="post" role="form">
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens="only") }}
            {{ wtf.form_field(form.username, class='form-control', placeholder='Your username...')}}
            {{ wtf.form_field(form.password, class='form-control', placeholder='Your password')}}
            {{ wtf.form_field(form.password2, class='form-control', placeholder='Repeat password')}}
            {{ wtf.form_field(form.submit, class='btn btn-success') }}
        </form>
    </div>
</div>
{% endblock %}