app/trackerapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, MultipleFileField, TextAreaField, SelectField,SelectMultipleField
from wtforms.validators import DataRequired
from .lookup import *


class AddTrackerForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    priority = SelectField('Priority', choices = Lookup(PRIORITIES))
    project = SelectField('Project', validators=[DataRequired()])
    user_assigned = SelectField('Assigned to', validators=[DataRequired()])
    categories = SelectMultipleField('Categories',choices=Lookup(CATEGORIES))
    images = MultipleFileField('Images')
    submit = SubmitField('Submit')


class EditTrackerForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    status = SelectField('Status', choices =Lookup(STATUSES))
    priority = SelectField('Priority', choices =Lookup(PRIORITIES))
    project = SelectField('Project', validators=[DataRequired()])
    user_assigned = SelectField('Assigned to', validators=[DataRequired()])
    categories = SelectMultipleField('Categories',choices=Lookup(CATEGORIES))
    images = MultipleFileField('Images')
    submit = SubmitField('Submit')

app/trackerapp/__init__.py
from flask import Blueprint

bp = Blueprint('trackerapp', __name__)

from app.trackerapp import routes

app/trackerapp/routes.py
from app.trackerapp import bp
from flask import url_for, request, render_template, send_from_directory, current_app, flash, redirect, session
from werkzeug.utils import secure_filename
from flask_login import login_required, current_user
from app.trackerapp.forms import AddTrackerForm, EditTrackerForm
from app.tracker import Tracker
from app.projectmodel import TrkProject
from app.usermodel import User
from app.trackerchangesmodel import TrkChanges
import os
from .lookup import *


@bp.route('/')
@login_required
def index():
    filt = {}
    if 'sessionproject' in session:
        if session['sessionproject'] != 'ALL':
            filt = {'project': session['sessionproject']}
    page = request.args.get('page', 1, type=int)
    changes = TrkChanges.get_list_changes(page, int(current_app.config['TRACKER_PER_PAGE']), filt)
    prev_url = url_for('trackerapp.index', page=changes.prev) if changes.has_prev else None
    next_url = url_for('trackerapp.index', page=changes.next) if changes.has_next else None
    return render_template('trackerapp/listchanges.html', title='Last changes',
                           prev_url=prev_url, next_url=next_url, changes=changes.changes)


@bp.route('/trackerlist/<filter_tracker>')
@login_required
def trackerlist(filter_tracker):
    filtering = {}
    if 'sessionproject' in session:
        if session['sessionproject'] != 'ALL':
            filtering = {'project': session['sessionproject']}
    if filter_tracker == 'open':
        filtering.update({'status': {'$in': [0, 1]}})
    if filter_tracker == 'closed':
        filtering.update({'status': {'$nin': [0, 1]}})
    page = request.args.get('page', 1, type=int)
    trackers = Tracker.get_list_trackers(page, int(current_app.config['TRACKER_PER_PAGE']), filtering=filtering)
    prev_url = url_for('trackerapp.trackerlist', filter_tracker=filter_tracker, page=trackers.prev) \
        if trackers.has_prev else None
    next_url = url_for('trackerapp.trackerlist', filter_tracker=filter_tracker, page=trackers.next) \
        if trackers.has_next else None
    return render_template('trackerapp/trackerlist.html', title='Trackers',
                           prev_url=prev_url, next_url=next_url, trackers=trackers.trackers, statuses=dict(STATUSES),
                           priorities=dict(PRIORITIES), categories=dict(CATEGORIES))


@bp.route('/tracker/<id>')
@login_required
def tracker(id):
    tracker = Tracker.get_tracker(id)
    return render_template('trackerapp/tracker.html', tracker=tracker, title=Tracker.title)


@bp.route('/tracker/<id>/popup')
@login_required
def tracker_popup(id):
    tracker = Tracker.get_tracker(id)
    if tracker is not None:
        return render_template('trackerapp/tracker_popup.html', tracker=tracker)
    return redirect(url_for('trackerapp.trackerlist', filter_tracker='open'))


@bp.route('/tracker_info/<id>', methods=['GET', 'POST'])
@login_required
def tracker_info(id):
    tracker = Tracker.get_tracker(id)
    if tracker is None:
        flash('tracker with id {} does not exist'.format(id))
        return redirect(url_for('trackerapp.trackerlist', filter_tracker='open'))
    if request.method == 'POST':
        if request.form['action'] == 'edit':
            return redirect(url_for('trackerapp.tracker_edit', id=tracker.id))
        elif request.form['action'] == 'back':
            return redirect(url_for('trackerapp.trackerlist', filter_tracker='open'))
        else:
            flash('Something strange happened here')
            return redirect(url_for('trackerapp.trackerlist'))
    else:
        return render_template('trackerapp/tracker_info.html', tracker=tracker, title=Tracker.title,
                               statuses=dict(STATUSES), priorities=dict(PRIORITIES), categories=dict(CATEGORIES))


@bp.route('/tracker_edit/<id>', methods=['GET', 'POST'])
@login_required
def tracker_edit(id):
    tracker = Tracker.get_tracker(id)
    if tracker is None:
        flash('tracker with id {} does not exist'.format(id))
        return redirect(url_for('trackerapp.trackerlist', filter_tracker='open'))
    form = EditTrackerForm(obj=tracker)
    form.project.choices = [(p.id, p.name) for p in TrkProject.get_all()]
    form.user_assigned.choices = [(u.username, u.username) for u in User.get_list_enabled_users()]
    if not form.project.choices:
        flash('No Projects exist!')
        return redirect(url_for('projects.projectlist'))
    if form.validate_on_submit():
        tracker.title = form.title.data
        tracker.description = form.description.data
        tracker.priority = int(form.priority.data)
        tracker.status = int(form.status.data)
        tracker.project = form.project.data
        tracker.user_assigned = form.user_assigned.data
        tracker.prefix = TrkProject.get_project(tracker.project).prefix
        tracker.categories = form.categories.data
        files = form.images.data
        action = 'EDITED'
        for f in files:
            if f is not None and not f == '':
                filename = secure_filename(f.filename)
                if allowed_file(filename):
                    if filename not in tracker.filenames:
                        tracker.filenames.append(filename)
                    if not os.path.exists(os.path.join(current_app.config['UPLOAD_FOLDER'], tracker.id)):
                        os.mkdir(os.path.join(current_app.config['UPLOAD_FOLDER'], tracker.id))
                    f.save(os.path.join(current_app.config['UPLOAD_FOLDER'], tracker.id,
                                        filename))
                    action = 'ADDED IMAGES'
                    tracker.user_assigned = current_user.username
                    if tracker.status == 0:
                        tracker.status = 1  #working
                else:
                    flash('File {} skipped because not image'.format(filename))
        tracker.update_tracker_by_form()
        flash('Tracker  {} updated'.format(tracker.number))
        TrkChanges.create_change(current_user.username, tracker, tracker.project, action)
        return redirect(url_for('trackerapp.trackerlist', filter_tracker='open'))
    else:
        return render_template('trackerapp/tracker_edit.html', form=form, tracker=tracker, title=Tracker.title)


@bp.route('/add_tracker', methods=['GET', 'POST'])
@login_required
def add_tracker():
    form = AddTrackerForm()
    form.project.choices = [(p.id, p.name) for p in TrkProject.get_all()]
    form.user_assigned.choices = [(u.username, u.username) for u in User.get_list_enabled_users()]
    form.user_assigned.data = current_user.username
    if 'sessionproject' in session and session['sessionproject'] != 'ALL':
        form.project.data = session['sessionproject']
    if not form.project.choices:
        flash('No Projects exist!')
        return redirect(url_for('projects.projectlist', filter_tracker='open'))
    if form.validate_on_submit():
        tracker = Tracker.add_tracker(form.title.data, form.project.data)
        tracker.description = form.description.data
        tracker.priority = int(form.priority.data)
        tracker.project = form.project.data
        tracker.prefix = TrkProject.get_project(tracker.project).prefix
        tracker.categories = form.categories.data
        tracker.user_assigned = form.user_assigned.data
        files = form.images.data

        for f in files:
            if f is not None and not f == '':
                filename = secure_filename(f.filename)
                if allowed_file(filename):
                    tracker.filenames.append(filename)
                    if not os.path.exists(os.path.join(current_app.config['UPLOAD_FOLDER'], tracker.id)):
                        os.mkdir(os.path.join(current_app.config['UPLOAD_FOLDER'], tracker.id))
                    f.save(os.path.join(current_app.config['UPLOAD_FOLDER'], tracker.id,
                                        filename))
                else:
                    flash('File {} skipped because not image'.format(filename))
        tracker.update_tracker_by_form()
        TrkChanges.create_change(current_user.username, tracker, tracker.project, 'CREATED')
        return redirect(url_for('trackerapp.tracker_info', id=tracker.id))
    return render_template('trackerapp/add_tracker.html', form=form, title='Add tracker')


@bp.route('/delete_tracker/<id>', methods=['POST'])
@login_required
def delete_tracker(id):
    if current_user.admin:
        Tracker.get_tracker(id).remove_tracker()
        TrkChanges.create_change(current_user.username, tracker, tracker.project, 'DELETED')
    return redirect(url_for('trackerapp.trackerlist', filter_tracker='open'))


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS']


@bp.route('/uploads/<tracker_id>/<filename>')
def uploaded_file(tracker_id, filename):
    return send_from_directory(os.path.join(current_app.config['UPLOAD_FOLDER'], tracker_id),
                               filename)

app/templates/trackerapp/add_tracker.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Create Tracker</h1>
<div class="row">
    <div class="col-md-4">
        <form class="form form-vertical" method="post" role="form" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens="only") }}
            {{ wtf.form_field(form.title, class='form-control', placeholder='Title')}}
            <br>
			{{ wtf.form_field(form.description, class='form-control', placeholder='Description')}}
			{{ wtf.form_field(form.priority, class='form-control', placeholder='Priority')}}
			{{ wtf.form_field(form.categories, class='form-control', placeholder='Categories')}}
			{{ wtf.form_field(form.project, class='form-control', placeholder='Project')}}
            {{ wtf.form_field(form.user_assigned, class='form-control', placeholder='Assigned to')}}
			{{ wtf.form_field(form.images, class='form-control', placeholder='Image')}}
			 <br>
            {{ wtf.form_field(form.submit, class='btn btn-success') }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/trackerapp/listchanges.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Last tracker changes</h1>

<table class="table table-hover">
       <tr>
		<th>
			Tracker
		</th>
        <th>
            Changed by
        </th>
		<th>
            On
        </th>
		<th>
			Type of update
		</th>
    </tr>
    {% for change in changes %}

    <tr>
		<td>
        <div class="tracker_id">
                <a href="{{ url_for('trackerapp.tracker_info',id=change.tracker_id) }}">{{ change.tracker_identifier }}</a>
                <span hidden="True">{{ change.tracker_id }}</span>
            </div>
        </td>
        <td>
            <div class="username">
                {{ change.username }}
            </div>
        </td>
		<td class="datetime">
			{{ change.datetime }}
        </td>
        <td class="actiontype">
			{{ change.action }}
        </td>
    </tr>
    {% endfor %}
</table>
<nav aria-label="...">
    <ul class="pager">
        <li class="previous {% if not prev_url %} disabled {% endif %}">
            <a href="{{ prev_url or '#' }}">
                <span aria-hidden="true">&larr;</span>Newer
            </a>
        </li>
        <li class="next {% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}">
                <span aria-hidden="true">&rarr;</span>Older
            </a>
        </li>
    </ul>
</nav>
{% endblock %}
{% block scripts %}
    {{ super() }}
{% endblock %}

app/templates/trackerapp/tracker_edit.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Update Tracker {{ tracker.prefix }}-{{ '%04d' % tracker.number }}</h1>
<div class="row">
    <div class="col-md-4">
        <form class="form form-vertical" method="post" role="form" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ wtf.form_errors(form, hiddens="only") }}
            {{ wtf.form_field(form.title, class='form-control', placeholder='Title')}}
			<br>
			{{ wtf.form_field(form.description, class='form-control', placeholder='Description')}}
			{{ wtf.form_field(form.status, class='form-control', placeholder='Status')}}
			{{ wtf.form_field(form.priority, class='form-control', placeholder='Priority')}}
			{{ wtf.form_field(form.categories, class='form-control', placeholder='Categories')}}
			{{ wtf.form_field(form.project, class='form-control', placeholder='Project')}}
            {{ wtf.form_field(form.user_assigned, class='form-control', placeholder='Assigned to')}}
			{{ wtf.form_field(form.images, class='form-control', placeholder='Image')}}
            <br>
            {{ wtf.form_field(form.submit, class='btn btn-success') }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/trackerapp/tracker_info.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}

<div class="container">
    <h1>Tracker {{ tracker.prefix }}-{{ '%04d' % tracker.number }}</h1>
    <div class="row">
        <div class="col-lg-12 order-md-1">
            <ul class="list-group mb-1">
                <li class="list-group-item d-flex justify-content-between lh-condensed">
					 <h6 class="my-0"><b>Title</b></h6>
					<small class="text-muted">{{ tracker.title }}</small>
					<h6 class="my-0"><b>Description</b></h6>
					<small class="text-muted">{{ tracker.description }}</small>
					<h6 class="my-0"><b>Status</b></h6>
					<small class="text-muted">{{ statuses.get(tracker.status|string) }}</small>
					<h6 class="my-0"><b>Priority</b></h6>
					<small class="text-muted">{{ priorities.get(tracker.priority|string) }}</small>
					<h6 class="my-0"><b>Assigned to</b></h6>
					<small class="text-muted">{{ tracker.user_assigned }}</small>
					<h6 class="my-0"><b>Categories</b></h6>
					{% for category in tracker.categories %}
					<small class="text-muted">{{ categories.get(category) }}</small>
					<br>
					{% endfor %}
					<h6 class="my-0"><b>Images</b></h6>
					{% for filename in tracker.filenames %}
					<small class="text-muted">
					<a href="/uploads/{{ tracker.id }}/{{ filename }}">{{ filename }}</a></small>
					<br>
					{% endfor %}
					</li>
					<li class="list-group-item d-flex justify-content-between lh-condensed">
                    <form action="" method="POST" class=del-component>
                        <button class="btn btn-warning" name="action" value="edit">Edit</button>
                        <button class="btn btn-success" name="action" value="back">Back</button>
                    </form>
                    <br>
				</li>
            </ul>
        </div>
    </div>
</div>


{% endblock %}

app/templates/trackerapp/tracker_popup.html
<div class="container">
    <div class="row">
		<ul class="list-group mb-3">
			<li class="list-group-item d-flex justify-content-between lh-condensed">
				<h6 class="my-0">Description</h6>
				<small class="text-muted">{{ tracker.description }}</small>
			</li>
		  
		</ul>

	
    </div>
</div>

app/templates/trackerapp/trackerlist.html
{% extends "basetemplate.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block appcontent %}
<h1>Trackers list</h1>
<a href="{{ url_for('trackerapp.add_tracker') }}" class="btn btn-info" role="button">Add new Tracker</a>
<table class="table table-hover">
       <tr>
		<th>
			Tracker
		</th>
        <th>
            Title
        </th>
        <th>
            Tracker status
        </th>
		<th>
            Tracker priority
        </th>
        <th>
            Categories
        </th>
           <th>
            Assigned to
        </th>
        {% if current_user.admin %}
        <th>
            Delete
        </th>
        {% endif %}
    </tr>
    {% for tracker in trackers %}

    <tr>
		<td>
        <div class="tracker_id">
                <a href="{{ url_for('trackerapp.tracker_info',id=tracker.id) }}">{{ tracker.prefix }}-{{ '%04d' % tracker.number }}</a>
                <span hidden="True">{{ tracker.id }}</span>
            </div>
        </td>
        <td>
            <div class="tracker_title">
                <a href="{{ url_for('trackerapp.tracker_info',id=tracker.id) }}">{{ tracker.title }}</a>
                <span hidden="True">{{ tracker.id }}</span>
            </div>
        </td>
		<td class="tracker_status">
			{{ statuses.get(tracker.status|string) }}
        </td>
        <td class="tracker_priority">
			{{ priorities.get(tracker.priority|string) }}
        </td>
        <td class="tracker_categories">
			{% for category in tracker.categories %}
				{{ categories.get(category|string) }}{{"," if not loop.last }}
			{% endfor %}
        </td>
        		<td class="tracker_assignedTo">
			{{ tracker.user_assigned }}
        </td>
        {% if current_user.admin %}
        <td>
           <form action="{{ url_for('trackerapp.delete_tracker', id=tracker.id) }}" method=post class=del-component>
                <button class="btn btn-danger">
                    Delete
                </button>
            </form>
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
<nav aria-label="...">
    <ul class="pager">
        <li class="previous {% if not prev_url %} disabled {% endif %}">
            <a href="{{ prev_url or '#' }}">
                <span aria-hidden="true">&larr;</span>Newer
            </a>
        </li>
        <li class="next {% if not next_url %} disabled{% endif %}">
            <a href="{{ next_url or '#' }}">
                <span aria-hidden="true">&rarr;</span>Older
            </a>
        </li>
    </ul>
</nav>
{% endblock %}
{% block scripts %}
    {{ super() }}
{% endblock %}